language: php
php:
- 7.0
branches:
  only:
  - master
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 2.0
  - 3.0
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/before_install.sh
- "$TRAVIS_BUILD_DIR/scripts/travis/before_install.sh"
script:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/build.sh
- "$TRAVIS_BUILD_DIR/scripts/travis/build.sh"
env:
  global:
    secure: 1zcb6kORwqPAIP1rPCHWqQkddfntdbi3E/JXBQdV3rgQy+WJgMYIaeeUIhL8CBeIKAuNjkJ+Bv5L/IaresJGa/m29u8bBwt63oBYHH0hn/drtE/jPTcRwysL+aAESCh1gcWbHOa9WtS2UbloBGGuFB18TOFLWNIxFthyMSsq5FxCCPSxZAMR8T8yhQ6mxT8EyYbk61nAXNbNqT2lIw7RfwafX87FRKd7yMBLP3uxQL1wRvnaBPt8N1/GgL721pfw2/rIbPkDRnENRb2eXmPMUfdqfq48Bo1pfhR/QNl3uD89BV13N9yV1DTvIenn9AsAYh+A1/mymJfCJk0UPaikvEjlwM2b+Q7TYxzuGsd1lMUOIm6Z5OUhEZ8xHj1C/8NknohLtvPJCiCxKnqLIEJW+kXs0vAFiGUwKwMqdxlRujdpvInq+f+IUGFCNS0Q7xbSFzOpzA99zEOMsjJ82BIlxKNz4cZzhjYwEtW4c1n4kMqjhRi+dmtUhAmx5L4KqBLnSibMO3xrjWXXGuRLHQ3YLCSP/4nWBQ0z/Ha/k6lwPJ68ppm6QN9vsSmZ+kIH+9FKQnSoFF/nULbtFj4ZdBQ5M3M22axgif5KR6/t8vx93ofnzJ3lAh8V1U2pbnW5sZlePysGTOzHoUU4rxLRcueAjvdDaAhJPySKOSffbjaVObA=
